<?php

return [
	'mode'                     => '',
	'format'                   => 'A4',
	'default_font_size'        => '10',
	'default_font'             => 'arial',
	'margin_left'              => 5,
	'margin_right'             => 5,
	'margin_top'               => 10,
	'margin_bottom'            => 10,
	'margin_header'            => 0,
	'margin_footer'            => 0,
	'orientation'              => 'L',
	'title'                    => 'Laravel mPDF',
	'subject'                  => '',
	'author'                   => '',
	'watermark'                => '',
	'show_watermark'           => false,
	'show_watermark_image'     => false,
	'watermark_font'           => 'arial',
	'display_mode'             => 'fullpage',
	'watermark_text_alpha'     => 0.1,
	'watermark_image_path'     => '',
	'watermark_image_alpha'    => 0.2,
	'watermark_image_size'     => 'D',
	'watermark_image_position' => 'P',
	'custom_font_dir'          => '',
	'custom_font_data'         => [],
	'auto_language_detection'  => true,
	'temp_dir'                 => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),
	'pdfa'                     => false,
	'pdfaauto'                 => false,
	'use_active_forms'         => false,
];
